@file:Suppress("ClassName")

package ooo.jtc

import org.junit.jupiter.api.Tag

//@formatter:off
@Tag("UTILS")                                               annotation class UTILS
@UTILS                 @Tag("UTILS_PURGE_DATABASE")         annotation class UTILS_PURGE_DATABASE
@UTILS                 @Tag("UTILS_CREATE_AT_USERS")        annotation class UTILS_CREATE_AT_USERS
@UTILS                 @Tag("UTILS_CREATE_LT_USERS")        annotation class UTILS_CREATE_LT_USERS
@UTILS                 @Tag("UTILS_CLEAN_AT_DATA")          annotation class UTILS_CLEAN_AT_DATA

@Tag("BE")                                                  annotation class BE

@BE                 @Tag("BE_CUR_TRANSFER")                 annotation class BE_CUR_TRANSFER
@BE_CUR_TRANSFER    @Tag("BE_CUR_TRANSFER_CRUD")            annotation class BE_CUR_TRANSFER_CRUD

@BE                 @Tag("BE_SALARY_REGISTER")              annotation class BE_SALARY_REGISTER
@BE_SALARY_REGISTER @Tag("BE_SALARY_REGISTER_CRUD")         annotation class BE_SALARY_REGISTER_CRUD

@BE           @Tag("BE_RUPAYMENT")                          annotation class BE_RUPAYMENT
@BE_RUPAYMENT @Tag("BE_RUPAYMENT_CRUD")                     annotation class BE_RUPAYMENT_CRUD
@BE_RUPAYMENT @Tag("BE_RUPAYMENT_OTHER")                    annotation class BE_RUPAYMENT_OTHER
@BE_RUPAYMENT @Tag("BE_RUPAYMENT_FILTRATION")               annotation class BE_RUPAYMENT_FILTRATION
@BE_RUPAYMENT @Tag("BE_RUPAYMENT_SORTING")                  annotation class BE_RUPAYMENT_SORTING
@BE_RUPAYMENT @Tag("BE_RUPAYMENT_CATEGORIES")               annotation class BE_RUPAYMENT_CATEGORIES

@BE                @Tag("BE_LETTER_TO_BANK")                annotation class BE_LETTER_TO_BANK
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_CATEGORIES")     annotation class BE_LETTER_TO_BANK_CATEGORIES
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_CONTROLS")       annotation class BE_LETTER_TO_BANK_CONTROLS
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_CRUD")           annotation class BE_LETTER_TO_BANK_CRUD
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_EXPORT")         annotation class BE_LETTER_TO_BANK_EXPORT
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_FAVORITES")      annotation class BE_LETTER_TO_BANK_FAVORITES
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_FILTRATION")     annotation class BE_LETTER_TO_BANK_FILTRATION
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_HISTORY")        annotation class BE_LETTER_TO_BANK_HISTORY
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_LIFECYCLE")      annotation class BE_LETTER_TO_BANK_LIFECYCLE
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_OTHER")          annotation class BE_LETTER_TO_BANK_OTHER
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_PRINT")          annotation class BE_LETTER_TO_BANK_PRINT
@BE_LETTER_TO_BANK @Tag("BE_LETTER_TO_BANK_SORTING")        annotation class BE_LETTER_TO_BANK_SORTING

@BE                  @Tag("BE_LETTER_FROM_BANK")            annotation class BE_LETTER_FROM_BANK
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_CATEGORIES") annotation class BE_LETTER_FROM_BANK_CATEGORIES
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_CONTROLS")   annotation class BE_LETTER_FROM_BANK_CONTROLS
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_CRUD")       annotation class BE_LETTER_FROM_BANK_CRUD
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_EXPORT")     annotation class BE_LETTER_FROM_BANK_EXPORT
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_FAVORITES")  annotation class BE_LETTER_FROM_BANK_FAVORITES
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_FILTRATION") annotation class BE_LETTER_FROM_BANK_FILTRATION
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_HISTORY")    annotation class BE_LETTER_FROM_BANK_HISTORY
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_LIFECYCLE")  annotation class BE_LETTER_FROM_BANK_LIFECYCLE
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_OTHER")      annotation class BE_LETTER_FROM_BANK_OTHER
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_PRINT")      annotation class BE_LETTER_FROM_BANK_PRINT
@BE_LETTER_FROM_BANK @Tag("BE_LETTER_FROM_BANK_SORTING")    annotation class BE_LETTER_FROM_BANK_SORTING

@BE                 @Tag("BE_PUBLICATION")                  annotation class BE_PUBLICATION
@BE_PUBLICATION     @Tag("BE_PUBLICATION_CATEGORIES")       annotation class BE_PUBLICATION_CATEGORIES
@BE_PUBLICATION     @Tag("BE_PUBLICATION_CRUD")             annotation class BE_PUBLICATION_CRUD
@BE_PUBLICATION     @Tag("BE_PUBLICATION_CONTROLS")         annotation class BE_PUBLICATION_CONTROLS
@BE_PUBLICATION     @Tag("BE_PUBLICATION_LIFECYCLE")        annotation class BE_PUBLICATION_LIFECYCLE
@BE_PUBLICATION     @Tag("BE_PUBLICATION_OTHER")            annotation class BE_PUBLICATION_OTHER

@BE     @Tag("BE_UAA")                                      annotation class BE_UAA
@BE_UAA @Tag("BE_UAA_AUTHORIZATION")                        annotation class BE_UAA_AUTHORIZATION
@BE_UAA @Tag("BE_UAA_APPLICATION")                          annotation class BE_UAA_APPLICATION
@BE_UAA @Tag("BE_UAA_CATALOG")                              annotation class BE_UAA_CATALOG
@BE_UAA @Tag("BE_UAA_MFA")                                  annotation class BE_UAA_MFA
@BE_UAA @Tag("BE_UAA_RESOURCE")                             annotation class BE_UAA_RESOURCE
@BE_UAA @Tag("BE_UAA_SCOPE")                                annotation class BE_UAA_SCOPE
@BE_UAA @Tag("BE_UAA_USER")                                 annotation class BE_UAA_USER

@BE            @Tag("BE_DICTIONARY")                        annotation class BE_DICTIONARY

@BE_DICTIONARY @Tag("BE_DICTIONARY_ACCOUNT")                annotation class BE_DICTIONARY_ACCOUNT
@BE_DICTIONARY @Tag("BE_DICTIONARY_ACCOUNTTYPE")            annotation class BE_DICTIONARY_ACCOUNTTYPE
@BE_DICTIONARY @Tag("BE_DICTIONARY_BANKBIC")                annotation class BE_DICTIONARY_BANKBIC
@BE_DICTIONARY @Tag("BE_DICTIONARY_BANKINFO")               annotation class BE_DICTIONARY_BANKINFO
@BE_DICTIONARY @Tag("BE_DICTIONARY_BANKREPRESENTATIVE")     annotation class BE_DICTIONARY_BANKREPRESENTATIVE
@BE_DICTIONARY @Tag("BE_DICTIONARY_BANKRU")                 annotation class BE_DICTIONARY_BANKRU
@BE_DICTIONARY @Tag("BE_DICTIONARY_BRANCH")                 annotation class BE_DICTIONARY_BRANCH
@BE_DICTIONARY @Tag("BE_DICTIONARY_BRANCHCUSTOMER")         annotation class BE_DICTIONARY_BRANCHCUSTOMER
@BE_DICTIONARY @Tag("BE_DICTIONARY_BRANCHREPRESENTATIVE")   annotation class BE_DICTIONARY_BRANCHREPRESENTATIVE
@BE_DICTIONARY @Tag("BE_DICTIONARY_BUDGETPAYERSTATUS")      annotation class BE_DICTIONARY_BUDGETPAYERSTATUS
@BE_DICTIONARY @Tag("BE_DICTIONARY_BUDGETREASONCODE")       annotation class BE_DICTIONARY_BUDGETREASONCODE
@BE_DICTIONARY @Tag("BE_DICTIONARY_CUSTOMERREPRESENTATIVE") annotation class BE_DICTIONARY_CUSTOMERREPRESENTATIVE
@BE_DICTIONARY @Tag("BE_DICTIONARY_CODEVO")                 annotation class BE_DICTIONARY_CODEVO
@BE_DICTIONARY @Tag("BE_DICTIONARY_AGREEMENT")              annotation class BE_DICTIONARY_AGREEMENT
@BE_DICTIONARY @Tag("BE_DICTIONARY_CONTRACTOR")             annotation class BE_DICTIONARY_CONTRACTOR
@BE_DICTIONARY @Tag("BE_DICTIONARY_CONTRACTORCONTACT")      annotation class BE_DICTIONARY_CONTRACTORCONTACT
@BE_DICTIONARY @Tag("BE_DICTIONARY_CONTRACTORPAYMENT")      annotation class BE_DICTIONARY_CONTRACTORPAYMENT
@BE_DICTIONARY @Tag("BE_DICTIONARY_CONTROLCODE")            annotation class BE_DICTIONARY_CONTROLCODE
@BE_DICTIONARY @Tag("BE_DICTIONARY_COUNTRY")                annotation class BE_DICTIONARY_COUNTRY
@BE_DICTIONARY @Tag("BE_DICTIONARY_CURRENCY")               annotation class BE_DICTIONARY_CURRENCY
@BE_DICTIONARY @Tag("BE_DICTIONARY_CUSTOMER")               annotation class BE_DICTIONARY_CUSTOMER
@BE_DICTIONARY @Tag("BE_DICTIONARY_CUSTOMERKPP")            annotation class BE_DICTIONARY_CUSTOMERKPP
@BE_DICTIONARY @Tag("BE_DICTIONARY_CUSTOMERTYPE")           annotation class BE_DICTIONARY_CUSTOMERTYPE
@BE_DICTIONARY @Tag("BE_DICTIONARY_KBK")                    annotation class BE_DICTIONARY_KBK
@BE_DICTIONARY @Tag("BE_DICTIONARY_GOZ_CONTRACT")           annotation class BE_DICTIONARY_GOZ_CONTRACT
@BE_DICTIONARY @Tag("BE_DICTIONARY_GROUND")                 annotation class BE_DICTIONARY_GROUND
@BE_DICTIONARY @Tag("BE_DICTIONARY_IDENTITY_DOC_TYPE")      annotation class BE_DICTIONARY_IDENTITY_DOC_TYPE
@BE_DICTIONARY @Tag("BE_DICTIONARY_INCOME_TYPE")            annotation class BE_DICTIONARY_INCOME_TYPE
@BE_DICTIONARY @Tag("BE_DICTIONARY_INDIVIDUAL")             annotation class BE_DICTIONARY_INDIVIDUAL
@BE_DICTIONARY @Tag("BE_DICTIONARY_LOCATIONTYPE")           annotation class BE_DICTIONARY_LOCATIONTYPE
@BE_DICTIONARY @Tag("BE_DICTIONARY_NDSCALCULATION")         annotation class BE_DICTIONARY_NDSCALCULATION
@BE_DICTIONARY @Tag("BE_DICTIONARY_NDSPERCENT")             annotation class BE_DICTIONARY_NDSPERCENT
@BE_DICTIONARY @Tag("BE_DICTIONARY_OKFS")                   annotation class BE_DICTIONARY_OKFS
@BE_DICTIONARY @Tag("BE_DICTIONARY_OKOPF")                  annotation class BE_DICTIONARY_OKOPF
@BE_DICTIONARY @Tag("BE_DICTIONARY_PAYMENTPRIORITY")        annotation class BE_DICTIONARY_PAYMENTPRIORITY
@BE_DICTIONARY @Tag("BE_DICTIONARY_PAYMENTTYPE")            annotation class BE_DICTIONARY_PAYMENTTYPE
@BE_DICTIONARY @Tag("BE_DICTIONARY_SALARYPAYMENTTYPE")      annotation class BE_DICTIONARY_SALARYPAYMENTTYPE
@BE_DICTIONARY @Tag("BE_DICTIONARY_SALARYEMPLOYEE")         annotation class BE_DICTIONARY_SALARYEMPLOYEE
@BE_DICTIONARY @Tag("BE_DICTIONARY_PERSON")                 annotation class BE_DICTIONARY_PERSON
@BE_DICTIONARY @Tag("BE_DICTIONARY_RESIDENCY_PERMIT_DOCUMENT_TYPE")
                                                            annotation class BE_DICTIONARY_RESIDENCY_PERMIT_DOCUMENT_TYPE
@BE_DICTIONARY @Tag("BE_DICTIONARY_RUREGION")               annotation class BE_DICTIONARY_RUREGION
@BE_DICTIONARY @Tag("BE_DICTIONARY_SWIFT")                  annotation class BE_DICTIONARY_SWIFT
@BE_DICTIONARY @Tag("BE_DICTIONARY_STMNTOPERATIONTYPE")     annotation class BE_DICTIONARY_STMNTOPERATIONTYPE
@BE_DICTIONARY @Tag("BE_DICTIONARY_TIMEZONE")               annotation class BE_DICTIONARY_TIMEZONE
@BE_DICTIONARY @Tag("BE_DICTIONARY_TRANSFER_TERM")          annotation class BE_DICTIONARY_TRANSFER_TERM
@BE_DICTIONARY @Tag("BE_DICTIONARY_TREASURY_ACCOUNT_TAX")   annotation class BE_DICTIONARY_TREASURY_ACCOUNT_TAX
@BE_DICTIONARY @Tag("BE_DICTIONARY_UER")                    annotation class BE_DICTIONARY_UER

@BE_DICTIONARY @Tag("BE_DICTIONARY_LETTER_TYPE_TO_BANK")    annotation class BE_DICTIONARY_LETTER_TYPE_TO_BANK
@BE_DICTIONARY @Tag("BE_DICTIONARY_LETTER_TYPE_FROM_BANK")  annotation class BE_DICTIONARY_LETTER_TYPE_FROM_BANK

@BE_DICTIONARY @Tag("BE_DICTIONARY_MAILGROUP")              annotation class BE_DICTIONARY_MAILGROUP
@BE_DICTIONARY_MAILGROUP
@Tag("BE_DICTIONARY_MAILGROUP_CONTROLS")                    annotation class BE_DICTIONARY_MAILGROUP_CONTROLS

@BE_DICTIONARY @Tag("BE_DICTIONARY_ACTIVITYTYPE")           annotation class BE_DICTIONARY_ACTIVITYTYPE

@BE        @Tag("BE_CRYPTO")                                annotation class BE_CRYPTO
@BE_CRYPTO @Tag("BE_CRYPTO_PROFILE")                        annotation class BE_CRYPTO_PROFILE

@BE        @Tag("BE_FS")                                    annotation class BE_FS

@BE             @Tag("BE_ROLEMODEL")                        annotation class BE_ROLEMODEL
@BE_ROLEMODEL   @Tag("BE_ROLEMODEL_PRIVILEGE")              annotation class BE_ROLEMODEL_PRIVILEGE
@BE_ROLEMODEL   @Tag("BE_ROLEMODEL_ACCESS_OBJECT")          annotation class BE_ROLEMODEL_ACCESS_OBJECT
@BE_ROLEMODEL   @Tag("BE_ROLEMODEL_ACCESS_OBJECT_TYPE")     annotation class BE_ROLEMODEL_ACCESS_OBJECT_TYPE
@BE_ROLEMODEL   @Tag("BE_ROLEMODEL_PRODUCT")                annotation class BE_ROLEMODEL_PRODUCT

@BE             @Tag("BE_ROLEMODEL_PRIVILEGEGROUP")         annotation class BE_ROLEMODEL_PRIVILEGEGROUP
@BE_ROLEMODEL   @Tag("BE_ROLEMODEL_ROLE")                   annotation class BE_ROLEMODEL_ROLE