@file:Suppress("ClassName")

package ooo.jtc

import org.junit.jupiter.api.Tag

//@formatter:off
@Tag("UI")                                                  annotation class UI

@UI            @Tag("UI_DICTIONARY")                        annotation class UI_DICTIONARY

@UI_DICTIONARY @Tag("UI_DICTIONARY_PAYMENTTYPE")            annotation class UI_DICTIONARY_PAYMENTTYPE
@UI_DICTIONARY @Tag("UI_DICTIONARY_BUDGETPAYERSTATUS")      annotation class UI_DICTIONARY_BUDGETPAYERSTATUS
@UI_DICTIONARY @Tag("UI_DICTIONARY_BUDGETREASONCODE")       annotation class UI_DICTIONARY_BUDGETREASONCODE
@UI_DICTIONARY @Tag("UI_DICTIONARY_KBK")                    annotation class UI_DICTIONARY_KBK
@UI_DICTIONARY @Tag("UI_DICTIONARY_CODEVO")                 annotation class UI_DICTIONARY_CODEVO
@UI_DICTIONARY @Tag("UI_DICTIONARY_PAYMENTPRIORITY")        annotation class UI_DICTIONARY_PAYMENTPRIORITY
@UI_DICTIONARY @Tag("UI_DICTIONARY_STATEMENTOPERATIONTYPE") annotation class UI_DICTIONARY_STATEMENTOPERATIONTYPE

@UI           @Tag("UI_RUPAYMENT")                          annotation class UI_RUPAYMENT
@UI_RUPAYMENT @Tag("UI_RUPAYMENT_CREATE")                   annotation class UI_RUPAYMENT_CREATE
@UI_RUPAYMENT @Tag("UI_RUPAYMENT_COPY")                     annotation class UI_RUPAYMENT_COPY
@UI_RUPAYMENT @Tag("UI_RUPAYMENT_SIGN")                     annotation class UI_RUPAYMENT_SIGN
@UI_RUPAYMENT @Tag("UI_RUPAYMENT_DELETE")                   annotation class UI_RUPAYMENT_DELETE
@UI_RUPAYMENT @Tag("UI_RUPAYMENT_SEND")                     annotation class UI_RUPAYMENT_SEND

@UI           @Tag("UI_LETTER_TO_BANK")                     annotation class UI_LETTER_TO_BANK
@UI_LETTER_TO_BANK @Tag("UI_LETTER_TO_BANK_EXPORT")         annotation class UI_LETTER_TO_BANK_EXPORT
@UI_LETTER_TO_BANK @Tag("UI_LETTER_TO_BANK_PRINT")          annotation class UI_LETTER_TO_BANK_PRINT
@UI_LETTER_TO_BANK @Tag("UI_LETTER_TO_BANK_RECALL")         annotation class UI_LETTER_TO_BANK_RECALL
@UI_LETTER_TO_BANK @Tag("UI_LETTER_TO_BANK_PROCESS")        annotation class UI_LETTER_TO_BANK_PROCESS
@UI_LETTER_TO_BANK @Tag("UI_LETTER_TO_BANK_SCROLLER")       annotation class UI_LETTER_TO_BANK_SCROLLER
@UI_LETTER_TO_BANK @Tag("UI_LETTER_TO_BANK_TABS")           annotation class UI_LETTER_TO_BANK_TABS

@UI_LETTER_TO_BANK_SCROLLER
@Tag("UI_LETTER_TO_BANK_SCROLLER_ACTIONS")                  annotation class UI_LETTER_TO_BANK_SCROLLER_ACTIONS
@UI_LETTER_TO_BANK_SCROLLER
@Tag("UI_LETTER_TO_BANK_SCROLLER_CATEGORIES")               annotation class UI_LETTER_TO_BANK_SCROLLER_CATEGORIES
@UI_LETTER_TO_BANK_SCROLLER
@Tag("UI_LETTER_TO_BANK_SCROLLER_FILTRATION")               annotation class UI_LETTER_TO_BANK_SCROLLER_FILTRATION
@UI_LETTER_TO_BANK_SCROLLER
@Tag("UI_LETTER_TO_BANK_SCROLLER_SORTING")                  annotation class UI_LETTER_TO_BANK_SCROLLER_SORTING

@UI           @Tag("UI_LETTER_FROM_BANK")                   annotation class UI_LETTER_FROM_BANK
@UI_LETTER_FROM_BANK @Tag("UI_LETTER_FROM_BANK_EXPORT")     annotation class UI_LETTER_FROM_BANK_EXPORT
@UI_LETTER_FROM_BANK @Tag("UI_LETTER_FROM_BANK_PRINT")      annotation class UI_LETTER_FROM_BANK_PRINT
@UI_LETTER_FROM_BANK @Tag("UI_LETTER_FROM_BANK_SCROLLER")   annotation class UI_LETTER_FROM_BANK_SCROLLER
@UI_LETTER_FROM_BANK @Tag("UI_LETTER_FROM_BANK_TABS")       annotation class UI_LETTER_FROM_BANK_TABS
@UI_LETTER_FROM_BANK_SCROLLER
@Tag("UI_LETTER_FROM_BANK_SCROLLER_ACTIONS")                annotation class UI_LETTER_FROM_BANK_SCROLLER_ACTIONS
@UI_LETTER_FROM_BANK_SCROLLER
@Tag("UI_LETTER_FROM_BANK_SCROLLER_CATEGORIES")             annotation class UI_LETTER_FROM_BANK_SCROLLER_CATEGORIES

@UI_LETTER_FROM_BANK_SCROLLER
@Tag("UI_LETTER_FROM_BANK_SCROLLER_SORTING")                annotation class UI_LETTER_FROM_BANK_SCROLLER_SORTING
//@formatter:on