package ooo.jtc.aspectj

import ooo.jtc.extensions.postgresFormat
import org.aspectj.lang.ProceedingJoinPoint
import org.aspectj.lang.annotation.Around
import org.aspectj.lang.annotation.Aspect
import kotlin.jvm.Throws

@Aspect
class GenerexRandomControl {

    /**
     * Formatting random generated by [Generex] data.
     */
    @Around("execution(* com.mifmif.common.regex.Generex.random(..))")
    @Throws(Throwable::class)
    fun handleRandom(joinPoint: ProceedingJoinPoint): String {
        return joinPoint.proceed().toString().postgresFormat()
    }

}